version: '3.8'

services:

  ms-eureka-svc:
    image: ms-eureka-svc:latest
    container_name: ms-eureka-svc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_EUREKA_DEFAULT_ZONE: http://ms-eureka-svc:8761/eureka/
      SPRING_EUREKA_HOST_NAME: ms-eureka-svc
      SPRING_EUREKA_PORT: 8761
    ports:
      - "8761:8761"
    networks:
      - backend-net

networks:
  backend-net:
    external: true
